/**
 * Utility to format Teams summary data as Microsoft Teams Adaptive Cards
 * Adaptive Cards documentation: https://adaptivecards.io/
 */

import { TeamsSummaryData, AdaptiveCardPayload, AdaptiveCardElement } from '../types/teams.types';
import { formatDateIST } from './timezone.util';

/**
 * Format decimal hours to display format (e.g., 4.5 -> "4.5h", 8 -> "8.0h")
 */
function formatHours(hours: number): string {
  return `${hours.toFixed(1)}h`;
}

/**
 * Convert team summary data to Microsoft Teams Adaptive Card format
 *
 * Creates a rich, formatted message card with:
 * - Title with date
 * - Team name and total hours
 * - Section for each user with their tasks
 * - Visual separators and formatting
 *
 * @param summary - The team summary data to format
 * @returns Adaptive Card payload ready to send to Teams webhook
 */
export function formatTeamsSummaryCard(summary: TeamsSummaryData): AdaptiveCardPayload {
  const cardBody: AdaptiveCardElement[] = [];

  // Title: "Daily Summary - [Date]"
  cardBody.push({
    type: 'TextBlock',
    text: `Daily Summary - ${formatDateIST(summary.date)}`,
    size: 'extraLarge',
    weight: 'bolder',
    color: 'accent',
    wrap: true,
  });

  // Team name and total hours
  cardBody.push({
    type: 'FactSet',
    facts: [
      {
        title: 'Team',
        value: summary.teamName,
      },
      {
        title: 'Total Actual Time',
        value: formatHours(summary.totalTeamActualTime),
      },
      {
        title: 'Total Tracked Time',
        value: formatHours(summary.totalTeamTrackedTime),
      },
    ],
    separator: true,
    spacing: 'medium',
  });

  // User sections
  summary.userSummaries.forEach((userSummary, index) => {
    // User header
    cardBody.push({
      type: 'TextBlock',
      text: `${userSummary.userName} (${formatHours(userSummary.totalActualTime)} actual, ${formatHours(userSummary.totalTrackedTime)} tracked)`,
      size: 'large',
      weight: 'bolder',
      separator: true,
      spacing: 'medium',
      wrap: true,
    });

    // User's tasks grouped by project
    const tasksByProject = new Map<string, typeof userSummary.tasks>();
    userSummary.tasks.forEach(task => {
      const projectTasks = tasksByProject.get(task.projectName) || [];
      projectTasks.push(task);
      tasksByProject.set(task.projectName, projectTasks);
    });

    // Display tasks grouped by project
    tasksByProject.forEach((tasks, projectName) => {
      // Project name
      cardBody.push({
        type: 'TextBlock',
        text: `**${projectName}**`,
        size: 'medium',
        weight: 'bolder',
        spacing: 'small',
        wrap: true,
      });

      // Tasks under this project
      tasks.forEach(task => {
        const taskText = `• ${task.taskDescription} - ${formatHours(task.actualTime)} (actual) / ${formatHours(task.trackedTime)} (tracked)`;
        cardBody.push({
          type: 'TextBlock',
          text: taskText,
          spacing: 'none',
          wrap: true,
        });
      });
    });
  });

  // Footer
  cardBody.push({
    type: 'TextBlock',
    text: 'Generated by Daily Report System',
    size: 'small',
    color: 'default',
    separator: true,
    spacing: 'medium',
    wrap: true,
  });

  // Construct the Adaptive Card payload
  const payload: AdaptiveCardPayload = {
    type: 'message',
    attachments: [
      {
        contentType: 'application/vnd.microsoft.card.adaptive',
        content: {
          type: 'AdaptiveCard',
          version: '1.4',
          body: cardBody,
        },
      },
    ],
  };

  return payload;
}
