/**
 * Utility to format Teams summary data as Microsoft Teams Adaptive Cards
 * Adaptive Cards documentation: https://adaptivecards.io/
 */

import { TeamsSummaryData, AdaptiveCardPayload, AdaptiveCardElement } from '../types/teams.types';
import { formatDateIST } from './timezone.util';

/**
 * Format time value to HH:MM display format
 * Handles both string (HH:MM) and number (decimal hours) formats for backward compatibility
 *
 * @param time - Time as string ("HH:MM") or number (decimal hours)
 * @returns Formatted time string (e.g., "3:30", "0:45", "12:15")
 */
function formatTime(time: string | number): string {
  // If it's already a string in HH:MM format, return as-is
  if (typeof time === 'string') {
    return time;
  }

  // If it's a number (decimal hours), convert to HH:MM format
  // For backward compatibility with old decimal format
  const hours = Math.floor(time);
  const minutes = Math.round((time - hours) * 60);

  // Handle edge case where rounding gives us 60 minutes
  if (minutes === 60) {
    return `${hours + 1}:00`;
  }

  const paddedMinutes = minutes.toString().padStart(2, '0');
  return `${hours}:${paddedMinutes}`;
}

/**
 * Convert team summary data to Microsoft Teams Adaptive Card format
 *
 * Creates a rich, formatted message card with:
 * - Title with date
 * - Team name and total hours
 * - Section for each user with their tasks
 * - Visual separators and formatting
 *
 * @param summary - The team summary data to format
 * @returns Adaptive Card payload ready to send to Teams webhook
 */
export function formatTeamsSummaryCard(summary: TeamsSummaryData): AdaptiveCardPayload {
  const cardBody: AdaptiveCardElement[] = [];

  // Title: "Daily Summary - [Date]"
  cardBody.push({
    type: 'TextBlock',
    text: `Daily Summary - ${formatDateIST(summary.date)}`,
    size: 'extraLarge',
    weight: 'bolder',
    color: 'accent',
    wrap: true,
  });

  // Team name and total hours
  cardBody.push({
    type: 'FactSet',
    facts: [
      // {
      //   title: 'Team',
      //   value: summary.teamName,
      // },
      {
        title: 'Total Actual Time',
        value: formatTime(summary.totalTeamActualTime),
      },
      {
        title: 'Total Tracked Time',
        value: formatTime(summary.totalTeamTrackedTime),
      },
    ],
    separator: true,
    spacing: 'medium',
  });

  // User sections
  summary.userSummaries.forEach((userSummary, index) => {
    // User header
    cardBody.push({
      type: 'TextBlock',
      // text: `${userSummary.userName} (${formatHours(userSummary.totalActualTime)} actual, ${formatHours(userSummary.totalTrackedTime)} tracked)`,
      text: `${userSummary.userName}`,
      size: 'large',
      weight: 'bolder',
      separator: true,
      spacing: 'medium',
      wrap: true,
    });

    // User's tasks grouped by project
    const tasksByProject = new Map<string, typeof userSummary.tasks>();
    userSummary.tasks.forEach(task => {
      const projectTasks = tasksByProject.get(task.projectName) || [];
      projectTasks.push(task);
      tasksByProject.set(task.projectName, projectTasks);
    });

    // Display tasks grouped by project
    tasksByProject.forEach((tasks, projectName) => {
      // Calculate total tracked time for this project
      const projectTrackedTime = tasks.reduce((sum, task) => {
        const time = typeof task.trackedTime === 'string' ? parseFloat(task.trackedTime) : task.trackedTime;
        return sum + time;
      }, 0);

      // Project name with total time
      cardBody.push({
        type: 'TextBlock',
        text: `**${projectName} [${formatTime(projectTrackedTime)}]**`,
        size: 'medium',
        weight: 'bolder',
        spacing: 'small',
        wrap: true,
      });

      // Tasks under this project
      tasks.forEach(task => {
        // const taskText = `• ${task.taskDescription} - ${formatHours(task.actualTime)} (actual) / ${formatHours(task.trackedTime)} (tracked)`;
        const taskText = `${task.taskDescription}`;
        cardBody.push({
          type: 'TextBlock',
          text: taskText,
          spacing: 'none',
          wrap: true,
        });
      });
    });
  });

  // Footer
  cardBody.push({
    type: 'TextBlock',
    text: 'Generated by Daily Report System',
    size: 'small',
    color: 'default',
    separator: true,
    spacing: 'medium',
    wrap: true,
  });

  // Construct the Adaptive Card payload
  const payload: AdaptiveCardPayload = {
    type: 'message',
    attachments: [
      {
        contentType: 'application/vnd.microsoft.card.adaptive',
        content: {
          type: 'AdaptiveCard',
          version: '1.4',
          body: cardBody,
        },
      },
    ],
  };

  return payload;
}
